version=0.1

[default.global.parameters]
stack_name = "hello-aws-golang-dev"

[default.deploy.parameters]
stack_name = "hello-aws-golang-dev"
#s3_bucket = "my-source-bucket"
#s3_prefix = "my-s3-prefix"
#image_repositories = ["my-function-1=image-repo-1", "my-function-2=image-repo-2"]
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
tags = "project=\"hello-aws-golang-application\" stage=\"dev\""
