version = 0.1
[default.global.parameters]
stack_name = "hello-aws-golang-dev"

[default.deploy.parameters]
stack_name = "hello-aws-golang-dev"
#s3_bucket = "hello-aws-golang-source-bucket"
#s3_prefix = "hello-aws-golang-s3-prefix"
##image_repositories = ["hello-function-1=image-repo-1", "world-function-2=image-repo-2"]
region = "eu-central-1"
#confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "project=\"hello-aws-golang-application\" stage=\"dev\""