service: hello-aws-golang

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: us-east-1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  HelloFunction:
    handler: bin/hello
    events:
      - httpApi:
          path: /hello
          method: get
  WorldFunction:
    handler: bin/world
    events:
      - httpApi:
          path: /world
          method: get

